const express=require('express');
const Router = express.Router();
const dataproject = require('../Services/dataproject');

Router.get('/projectmanager/:id',dataproject.getproject)
Router.get('/projectleader/:id',dataproject.projectleader)
Router.get('/projectuser/:id',dataproject.projectuser)
Router.get('/projectdirector',dataproject.projectdiector)
Router.get('/fiscalyear',dataproject.fiscalyear)
Router.get('/project',dataproject.project)
Router.get('/sectionproject/:id',dataproject.sectionproject)
Router.get('/userproject/:id',dataproject.userproject)
Router.get('/strategicplanproject/:id',dataproject.strategicplanproject)
Router.get('/strategicproject/:id',dataproject.strategicproject)
Router.get('/goalproject/:id',dataproject.goalproject)
Router.get('/tacticproject/:id',dataproject.tacticproject)
Router.get('/integrationproject/:id',dataproject.integrationproject)
Router.get('/objectiveproject/:id',dataproject.objectiveproject)
Router.get('/indicproject/:id',dataproject.indicproject)
Router.get('/stepproject/:id',dataproject.stepproject)
Router.get('/workplanproject/:id',dataproject.workplanproject)
Router.get('/chargesproject/:id',dataproject.chargesproject)
Router.get('/benefitproject/:id',dataproject.benefitproject)
Router.get('/commentproject/:id',dataproject.commentproject)
Router.put('/confirmproject/:id',dataproject.confirmproject)
Router.put('/noconfirmproject/:id',dataproject.noconfirmproject)
Router.post('/comment',dataproject.comment)
Router.get('/projecttor',dataproject.projecttor)
Router.get('/deleteprojectid',dataproject.deleteprojectid)
Router.delete('/deleteproject/:ID',dataproject.deleteproject)
Router.get('/showproject/:id',dataproject.showproject)
Router.put('/openreportone/:id',dataproject.openreportone)
Router.put('/openreporttwo/:id',dataproject.openreporttwo)
Router.put('/openreportthree/:id',dataproject.openreportthree)
Router.put('/openreportfour/:id',dataproject.openreportfour)
Router.put('/closeproject/:id',dataproject.closeproject)
Router.get('/findproject/:year/:status',dataproject.findproject)
Router.get('/findprojectyear/:year',dataproject.findprojectyear)
Router.put('/notproject/:id',dataproject.notproject)
Router.post('/notcomment',dataproject.notcomment)
Router.get('/projectreport/:id',dataproject.projectreport)
Router.get('/pro/:id',dataproject.pro)

module.exports = Router