const express=require('express')
const env=require('dotenv').config()
const bodyparser=require('body-parser')
const dbConfig=require('./config/dbConfig')
const cors=require('cors')

const app=express()
const user=require('./Routes/userRouter')
const agency = require('./routes/manageRouter')
const mangeuser = require('./routes/manageUser') 
const pland = require('./routes/plandof')
const editstg = require('./routes/editstgroute')
const projectrout = require('./routes/projectroute')
const dataproject = require('./routes/dataProject')
const datareport = require('./routes/dataReport')
const supplies = require('./routes/Supplies')
const editproject = require('./routes/editProject')
const addreport = require('./routes/addReport')
const editreport = require('./routes/editReport')
const dataevaluation = require('./routes/dataEvaluation')
const editmanager = require('./routes/editManager')
const datakeepproject = require('./routes/dataKeepproject')
const editkeepreport = require('./routes/editKeepreport')
const torfile = require('./routes/torFile')
const report = require('./routes/reportprojectroute')
const sendemail = require('./routes/sendemailroute')
app.use(bodyparser.json())
app.use(cors())
app.use('/user',user)
app.use('/',agency)
app.use('/manageuser',mangeuser)
app.use('/plan',pland)
app.use('/stg',editstg)
app.use('/new',projectrout)
app.use('/dataproject',dataproject)
app.use('/datareport',datareport)
app.use('/supplies',supplies)
app.use('/editproject',editproject)
app.use('/addreport',addreport)
app.use('/editreport',editreport)
app.use('/dataevaluation',dataevaluation)
app.use('/editmanager',editmanager)
app.use('/datakeepproject',datakeepproject)
app.use('/editkeepreport',editkeepreport)
app.use('/torfile',torfile)
app.use('/report',report)
app.use('/sendEmail',sendemail)

const PORT = 3001

app.listen(PORT, console.log(`server listing to the port ${PORT}`))